/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import prgs.conexion;

/**
 *
 * @author Pecozita
 */
public class contrato extends javax.swing.JFrame {
    conexion miconexion =new conexion();
    /**
     * Creates new form contrato
     */
    public contrato() {
        initComponents();
        this.setExtendedState(menumain.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        txtcontrato = new javax.swing.JLabel();
        preciocon = new javax.swing.JLabel();
        metodocon = new javax.swing.JLabel();
        fyhcon = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtpago = new javax.swing.JTextField();
        txtfyh = new javax.swing.JTextField();
        idcliente = new javax.swing.JLabel();
        idvendedor = new javax.swing.JLabel();
        condicon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcondiciones = new javax.swing.JTextPane();
        clausulacon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtclausulas = new javax.swing.JTextPane();
        botonedit = new javax.swing.JButton();
        botondelete = new javax.swing.JButton();
        botoncancel = new javax.swing.JButton();
        botonsave = new javax.swing.JButton();
        botonexit = new javax.swing.JButton();
        botonagg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTRATO!");

        txtcontrato.setText("CONTRATO UNICO DEL COMPRADOR!");

        preciocon.setText("PRECIO DEL VEHICULO");

        metodocon.setText("METODO DE PAGO");

        fyhcon.setText("FECHA Y HORA ");

        txtprecio.setEnabled(false);

        txtpago.setEnabled(false);

        txtfyh.setEnabled(false);

        idcliente.setText("ID CLIENTE");

        idvendedor.setText("ID VENDEDOR");

        condicon.setText("CONDICIONES");

        txtcondiciones.setEnabled(false);
        jScrollPane1.setViewportView(txtcondiciones);

        clausulacon.setText("CLAUSULAS");

        txtclausulas.setEnabled(false);
        jScrollPane2.setViewportView(txtclausulas);

        botonedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/editar.png"))); // NOI18N
        botonedit.setText("EDITAR");

        botondelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/borrar-auto.png"))); // NOI18N
        botondelete.setText("BORRAR");
        botondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondeleteActionPerformed(evt);
            }
        });

        botoncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/cancelar-auto.png"))); // NOI18N
        botoncancel.setText("CANCELAR");
        botoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelActionPerformed(evt);
            }
        });

        botonsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/grabar-auto.png"))); // NOI18N
        botonsave.setText("GRABAR");
        botonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsaveActionPerformed(evt);
            }
        });

        botonexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/cerrar-sesion.png"))); // NOI18N
        botonexit.setText("SALIR");
        botonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonexitActionPerformed(evt);
            }
        });

        botonagg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/agregar-auto.png"))); // NOI18N
        botonagg.setText("AGREGAR");
        botonagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaggActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        txt_codigo.setEnabled(false);
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(botonagg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idcliente)
                                .addGap(72, 72, 72)
                                .addComponent(idvendedor)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(preciocon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(metodocon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fyhcon)
                                    .addComponent(condicon)
                                    .addComponent(clausulacon))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtprecio)
                                    .addComponent(txtpago)
                                    .addComponent(txtfyh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(97, 97, 97)
                                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonsave, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botoncancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtcontrato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcliente)
                            .addComponent(idvendedor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfyh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(preciocon)
                                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(metodocon))
                                    .addComponent(txtpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(fyhcon)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condicon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clausulacon))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonagg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonedit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonsave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botondeleteActionPerformed

    private void botoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelActionPerformed
        hab_botones();
        des_text();
        clear_text();
    }//GEN-LAST:event_botoncancelActionPerformed

    private void botonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsaveActionPerformed
        hab_botones();
        des_text();
        clear_text();
    }//GEN-LAST:event_botonsaveActionPerformed

    private void botonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonexitActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(this, "DESEA SALIR", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }

    }//GEN-LAST:event_botonexitActionPerformed

    private void botonaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaggActionPerformed
        hab_text();
        des_botones();
        this.txtprecio.requestFocus();
        generar_codigo();
        operacion = "agregar"; 
        
    }//GEN-LAST:event_botonaggActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        buscar_codigo();
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contrato().setVisible(true);
            }
        });
    }

       private void hab_text() {
        txtprecio.setEnabled(true);
        txtpago.setEnabled(true);
        txtfyh.setEnabled(true);
        txtcondiciones.setEnabled(true);
        txtclausulas.setEnabled(true);
    }
    private void des_text() {
        txtprecio.setEnabled(false);
        txtpago.setEnabled(false);
        txtfyh.setEnabled(false);
        txtcondiciones.setEnabled(false);
        txtclausulas.setEnabled(false);
    }
    private void des_botones() {
          botonagg.setEnabled(false);
          botondelete.setEnabled(false);
          botonedit.setEnabled(false);
          botonexit.setEnabled(false);
  
          botonsave.setEnabled(true);
          botoncancel.setEnabled(true);
      }
    private void hab_botones() {
          botonagg.setEnabled(true);
          botondelete.setEnabled(true);
          botonedit.setEnabled(true);
          botonexit.setEnabled(true);
  
          botonsave.setEnabled(false);
          botoncancel.setEnabled(false);
      }
    private void clear_text() {
        txtprecio.setText("");
        txtpago.setText("");
        txtfyh.setText("");
        txtcondiciones.setText("");
        txtclausulas.setText("");
    }
        private String operacion= "";
         private void generar_codigo() 
     {
        try 
        {
             // habilita la variable para recibir sentencias  
            miconexion.sentencia = miconexion.conexion.createStatement();
                 
            miconexion.resultado = miconexion.sentencia.executeQuery("SELECT IFNULL(MAX(con_id),0) + 1  AS nuevocod FROM contrato");
            
            //etraer los datos de la variable
            while(miconexion.resultado.next()==true)
            {
                this.txt_codigo.setText(miconexion.resultado.getString("nuevocod"));
                
                // this.txt_codigo.setText("7777");
            }  
        } // generar cod
        catch (SQLException ex) {
            Logger.getLogger(registrarcli.class.getName()).log(Level.SEVERE, null, ex);
        } 
         
     }
     
     private void grabar_datos(){
          try { 
              miconexion.sentencia = miconexion.conexion.createStatement();          
              
              if(operacion.equals("agregar")){
                   miconexion.sentencia.executeUpdate("INSERT INTO "
                           + "contrato(con_id,usu_id ,ven_id ,cli_id ,aut_id ,con_precio , con_metodo ,con_fyh ) VALUES("+
                           this.txt_codigo.getText()+",'"+
                           this.txtprecio.getText()+"','"+
                           this.txtpago.getText()+"','"+
                           this.txtfyh.getText()+"','"+
                           this.txtcondiciones.getText()+"','"+
                           this.txtclausulas.getText()+"')");
                                           
                   JOptionPane.showMessageDialog(null, "El registro se ha insertado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
      
               }
              
              if(operacion.equals("editar")){
              
                   miconexion.sentencia.executeUpdate("UPDATE contrato SET con_precio = '"+
                           this.txtprecio.getText()+"', con_metodo = '"+
                           this.txtpago.getText()+"', con_fyh = '"+
                           this.txtfyh.getText()+"', tip_descrip = '"+
                           this.txtcondiciones.getText()+"', cla_descrip = '"+
                           this.txtclausulas.getText()+"' WHERE con_id ="+
                           this.txt_codigo.getText());
                                           
                   JOptionPane.showMessageDialog(null, "El registro se ha modificado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
      
               }
                                
        } catch (SQLException ex) {
            Logger.getLogger(registrarcli.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }


  private void buscar_codigo()
  {
    
        try 
        {
             boolean encontro = false;
             
            // habilita la variable para recibir sentencias
            miconexion.sentencia = miconexion.conexion.createStatement();
            
            miconexion.resultado = miconexion.sentencia.executeQuery("SELECT * FROM contrato WHERE con_id = "+this.txt_codigo.getText());
            
            //etraer los datos de la variable
            while(miconexion.resultado.next()==true)
            {   
                this.txtprecio.setText(miconexion.resultado.getString("cli_nom"));
                this.txtpago.setText(miconexion.resultado.getString("cli_ape"));
                this.txtfyh.setText(miconexion.resultado.getString("cli_ci"));
                this.txtcondiciones.setText(miconexion.resultado.getString("cli_direcc"));
                this.txtclausulas.setText(miconexion.resultado.getString("cli_direcc"));

                encontro = true;
            } 
            
            if(encontro==false)//no encontro
            {
                JOptionPane.showMessageDialog(null, "No existe contrato con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
                this.txt_codigo.setText("");
                this.txt_codigo.requestFocus(); 
            }//fin del if
            else // encontro
            {
              if(operacion.equals("editar"))
              {
                  this.txtprecio.requestFocus();
                  hab_text();
               }  
                
                if(operacion.equals("borrar"))
                 {
                    int respuesta = JOptionPane.showConfirmDialog(this,"Deseas Borrar el Registro?","Confirmar",JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION) // si
                     {
                          // habilitar 
                          miconexion.sentencia = miconexion.conexion.createStatement();
                          miconexion.sentencia.executeUpdate("DELETE FROM contrato WHERE con_id ="+this.txt_codigo.getText());

                          JOptionPane.showMessageDialog(null, "El registro se ha borrado satisfactoriamente.", "Playa De Autos", JOptionPane.INFORMATION_MESSAGE);

                          des_text();
                          hab_botones();
                          clear_text();

                      }
                      else // no 
                     {
                          JOptionPane.showMessageDialog(null, "La operacion ha sido cancelada", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);

                       //   this.btn_cancelar.doClick();
                          des_text();
                          hab_botones();
                          clear_text();  
                     } 
                 }     
            }    
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(registrarcli.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagg;
    private javax.swing.JButton botoncancel;
    private javax.swing.JButton botondelete;
    private javax.swing.JButton botonedit;
    private javax.swing.JButton botonexit;
    private javax.swing.JButton botonsave;
    private javax.swing.JLabel clausulacon;
    private javax.swing.JLabel condicon;
    private javax.swing.JLabel fyhcon;
    private javax.swing.JLabel idcliente;
    private javax.swing.JLabel idvendedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel metodocon;
    private javax.swing.JLabel preciocon;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextPane txtclausulas;
    private javax.swing.JTextPane txtcondiciones;
    private javax.swing.JLabel txtcontrato;
    private javax.swing.JTextField txtfyh;
    private javax.swing.JTextField txtpago;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
