
package formularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import prgs.conexion;


public class registrarven extends javax.swing.JFrame {
    conexion miconexion =new conexion();
    public registrarven() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtci = new javax.swing.JTextField();
        txtdirecc = new javax.swing.JTextField();
        nomven = new javax.swing.JLabel();
        apeven = new javax.swing.JLabel();
        civen = new javax.swing.JLabel();
        vendirecc = new javax.swing.JLabel();
        botonagg = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botonborrar = new javax.swing.JButton();
        botoncancelar = new javax.swing.JButton();
        botongrabar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR VENDEDOR!");

        txtnom.setToolTipText("");
        txtnom.setEnabled(false);
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });

        txtape.setToolTipText("");
        txtape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapeActionPerformed(evt);
            }
        });
        txtape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapeKeyTyped(evt);
            }
        });
        txtape.setEnabled(false);

        txtci.setToolTipText("");
        txtci.setEnabled(false);
        txtci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciKeyTyped(evt);
            }
        });

        txtdirecc.setToolTipText("");
        txtdirecc.setEnabled(false);
        txtdirecc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccKeyTyped(evt);
            }
        });

        nomven.setText("NOMBRE");
        nomven.setToolTipText("REGISTRAR CLIENTE!");

        apeven.setText("APELLIDO");
        apeven.setToolTipText("REGISTRAR CLIENTE!");

        civen.setText("CI");
        civen.setToolTipText("REGISTRAR CLIENTE!");

        vendirecc.setText("DIRECCION");
        vendirecc.setToolTipText("REGISTRAR CLIENTE!");

        botonagg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/agregar-vendedor.png"))); // NOI18N
        botonagg.setText("AGREGAR");
        botonagg.setToolTipText("");
        botonagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaggActionPerformed(evt);
            }
        });

        botoneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/editar.png"))); // NOI18N
        botoneditar.setText("EDITAR");
        botoneditar.setToolTipText(" ");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });

        botonborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/borrar.png"))); // NOI18N
        botonborrar.setText("BORRAR");
        botonborrar.setToolTipText(" ");
        botonborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonborrarActionPerformed(evt);
            }
        });

        botoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/cancelar.png"))); // NOI18N
        botoncancelar.setText("CANCELAR");
        botoncancelar.setToolTipText(" ");
        botoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncancelarActionPerformed(evt);
            }
        });

        botongrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/grabar.png"))); // NOI18N
        botongrabar.setText("GRABAR");
        botongrabar.setToolTipText(" ");
        botongrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botongrabarActionPerformed(evt);
            }
        });

        botonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playa_auto/Images/salida.png"))); // NOI18N
        botonsalir.setText("SALIR");
        botonsalir.setToolTipText(" ");
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        txt_codigo.setEnabled(false);
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomven, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apeven, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(civen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vendirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtci, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botoncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botoneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonagg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botongrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botonsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonagg, botonborrar, botongrabar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomven, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apeven, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(civen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vendirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdirecc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botoneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botoncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonagg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botongrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonagg, botonborrar, botoncancelar, botoneditar, botongrabar, botonsalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapeActionPerformed

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "DESEA SALIR", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botonaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaggActionPerformed
        hab_text();
        des_botones();
        this.txtnom.requestFocus();
        generar_codigo();
        operacion = "agregar";
    }//GEN-LAST:event_botonaggActionPerformed

    private void botoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncancelarActionPerformed
        hab_botones();
        des_text();
        clear_text();
    }//GEN-LAST:event_botoncancelarActionPerformed

    private void botongrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botongrabarActionPerformed
        grabar_datos();
        hab_botones();
        des_text();
        clear_text();
    }//GEN-LAST:event_botongrabarActionPerformed

    private void botonborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonborrarActionPerformed
        operacion = "borrar"; 
        des_botones();
        this.txt_codigo.setEnabled(true);
        this.txt_codigo.requestFocus();
    }//GEN-LAST:event_botonborrarActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        operacion = "editar"; 
        this.txt_codigo.setEnabled(true);
        this.txt_codigo.requestFocus();
        des_botones();
    }//GEN-LAST:event_botoneditarActionPerformed

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        buscar_codigo();
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != evt.VK_BACK_SPACE) {
            evt.consume(); // Ignorar el carácter
            JOptionPane.showMessageDialog(null, "Solo se permiten letras en el nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapeKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != ' ' && c != evt.VK_BACK_SPACE) {
            evt.consume(); // Ignorar el carácter
            JOptionPane.showMessageDialog(null, "Solo se permiten letras en el apellido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtapeKeyTyped

    private void txtciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != evt.VK_BACK_SPACE) {
            evt.consume(); // Ignorar el carácter
            JOptionPane.showMessageDialog(null, "Solo se permiten números en el CI", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtciKeyTyped

    private void txtdireccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccKeyTyped

    }//GEN-LAST:event_txtdireccKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarven().setVisible(true);
            }
        });
    }
    private String operacion= "";

       private void hab_text() {
        txtnom.setEnabled(true);
        txtape.setEnabled(true);
        txtci.setEnabled(true);
        txtdirecc.setEnabled(true);
    }
    private void des_text() {
        txtnom.setEnabled(false);
        txtape.setEnabled(false);
        txtci.setEnabled(false);
        txtdirecc.setEnabled(false);
        txt_codigo.setEnabled(false);
    }
       private void des_botones() {
        botonagg.setEnabled(false);
        botonborrar.setEnabled(false);
        botoneditar.setEnabled(false);
        botonsalir.setEnabled(false);

        botongrabar.setEnabled(true);
        botoncancelar.setEnabled(true);
    }
    private void hab_botones() {
        botonagg.setEnabled(true);
        botonborrar.setEnabled(true);
        botoneditar.setEnabled(true);
        botonsalir.setEnabled(true);

        botongrabar.setEnabled(false);
        botoncancelar.setEnabled(false);
    }
    private void clear_text() {
        txtnom.setText("");
        txtape.setText("");
        txtci.setText("");
        txtdirecc.setText("");
        txt_codigo.setText("");
    }
    private void generar_codigo(){
        try 
        {
             // habilita la variable para recibir sentencias  
            miconexion.sentencia = miconexion.conexion.createStatement();
                 
            miconexion.resultado = miconexion.sentencia.executeQuery("SELECT IFNULL(MAX(ven_id),0) + 1  AS nuevocod FROM vendedor");
            
            //etraer los datos de la variable
            while(miconexion.resultado.next()==true)
            {
                this.txt_codigo.setText(miconexion.resultado.getString("nuevocod"));
                
                // this.txt_codigo.setText("7777");
            }  
        } // generar cod
        catch (SQLException ex) {
            Logger.getLogger(registrarven.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
         private void grabar_datos(){
          try { 
              miconexion.sentencia = miconexion.conexion.createStatement();          
              
              if(operacion.equals("agregar")){
                   miconexion.sentencia.executeUpdate("INSERT INTO vendedor(ven_id,ven_nom,ven_ape,ven_ci,ven_direcc) VALUES("+this.txt_codigo.getText()+",'"+this.txtnom.getText()+"','"+this.txtape.getText()+"','"+this.txtci.getText()+"','"+this.txtdirecc.getText()+"')");
                                           
                   JOptionPane.showMessageDialog(null, "El registro se ha insertado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
      
               }
              
              if(operacion.equals("editar")){
              
                   miconexion.sentencia.executeUpdate("UPDATE vendedor SET ven_nom = '"+this.txtnom.getText()+"', ven_ape = '"+this.txtape.getText()+"', ven_ci = '"+this.txtci.getText()+"', ven_direcc = '"+this.txtdirecc.getText()+"' WHERE ven_id ="+this.txt_codigo.getText());
                                           
                   JOptionPane.showMessageDialog(null, "El registro se ha modificado satisfactoriamente.", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE);
      
               }
                                
        } catch (SQLException ex) {
            Logger.getLogger(registrarven.class.getName()).log(Level.SEVERE, null, ex);
        }
         
     }
    
private void buscar_codigo(){
    
        try 
        {
             boolean encontro = false;
             
            // habilita la variable para recibir sentencias
            miconexion.sentencia = miconexion.conexion.createStatement();
            
            miconexion.resultado = miconexion.sentencia.executeQuery("SELECT * FROM vendedor WHERE ven_id = "+this.txt_codigo.getText());
            
            //etraer los datos de la variable
            while(miconexion.resultado.next()==true)
            {   
                this.txtnom.setText(miconexion.resultado.getString("ven_nom"));
                this.txtape.setText(miconexion.resultado.getString("ven_ape"));
                this.txtci.setText(miconexion.resultado.getString("ven_ci"));
                this.txtdirecc.setText(miconexion.resultado.getString("ven_direcc"));

                encontro = true;
            } 
            
            if(encontro==false)//no encontro
            {
                JOptionPane.showMessageDialog(null, "No existe vendedor con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
                this.txt_codigo.setText("");
                this.txt_codigo.requestFocus(); 
            }//fin del if
            else // encontro
            {
              if(operacion.equals("editar"))
              {
                  this.txtnom.requestFocus();
                  hab_text();
               }  
                
                if(operacion.equals("borrar"))
                 {
                    int respuesta = JOptionPane.showConfirmDialog(this,"Deseas Borrar el Registro?","Confirmar",JOptionPane.YES_NO_OPTION);
                    if(respuesta == JOptionPane.YES_OPTION) // si
                     {
                          // habilitar 
                          miconexion.sentencia = miconexion.conexion.createStatement();
                          miconexion.sentencia.executeUpdate("DELETE FROM vendedor WHERE ven_id ="+this.txt_codigo.getText());

                          JOptionPane.showMessageDialog(null, "El registro se ha borrado satisfactoriamente.", "Playa De Autos", JOptionPane.INFORMATION_MESSAGE);

                          des_text();
                          hab_botones();
                          clear_text();

                      }
                      else // no 
                     {
                          JOptionPane.showMessageDialog(null, "La operacion ha sido cancelada", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);

                       //   this.btn_cancelar.doClick();
                          des_text();
                          hab_botones();
                          clear_text();  
                     } 
                 }     
            }    
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(registrarven.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeven;
    private javax.swing.JButton botonagg;
    private javax.swing.JButton botonborrar;
    private javax.swing.JButton botoncancelar;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botongrabar;
    private javax.swing.JButton botonsalir;
    private javax.swing.JLabel civen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomven;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtci;
    private javax.swing.JTextField txtdirecc;
    private javax.swing.JTextField txtnom;
    private javax.swing.JLabel vendirecc;
    // End of variables declaration//GEN-END:variables
}
